production:
  :concurrency: 5
:queues:
  - default
  - crawlers
:schedule:
   sync_bank_entries:
     cron: '0 0 * * * *'  # Runs once per hour
     class: SyncBankEntriesJob
   get_bsale_documents:
     every: '30m'
     class: GetBsaleDocumentsJob

